theme: jekyll-theme-leap-day
title:  Welcome to the Shape of Roman History Homepage!
Introduction: The Shape of Roman History project explores the history of Roman Republic through an analysis of the most up-to-date database of ancient persons available http://romanrepublic.ac.uk/. Through the existing rdf database, we were able to make new connections and gain a deeper insight into Roman life. The data visualizations in this project were created with D3 and Unity3D. This project is affiliated with the UCLA RomeLab romelab.etc.ucla.edu.


